serverUrl: https://blog.tunaxor.me
shortTitle: Tunaxor's Blog
title: Tunaxor's Blog
description: My Experiences on F#/JS and maybe other stuff as well
masterUserDisplayName: Angel D. Munoz
masterLanguage: en
languages: "en->ðŸ‡¬ðŸ‡§,es->ðŸ‡²ðŸ‡½"
users: "angelmunoz -> Angel D. Munoz"
